from src.Exceptions.ExceptionBase import ExceptionBase

class UrlNotFoundError(ExceptionBase):
    def __init__(self): pass
